# Site settings
title: HackLand
email: info@aucklandhackspace.nz
url: http://hackland.nz/
description: "A nest of tech, art, creativity and freedom"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: HackLand.nz

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: slack
    url: https://join.slack.com/hakland/shared_invite/MTkwOTk4MDI5NjUwLTE0OTYzMDE0NDYtNGNmMDMxZGUxNw
  - title: github
    url: https://github.com/HakLand/
  - title: twitter
    url: https://twitter.com/AKL_Hackspace/
  - title: facebook
    url: https://facebook.com/AuckHackspace/

# Build settings
markdown: kramdown
permalink: pretty
